cloud:
  aws:
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: carwashimagechnagminbucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: bjyg78x20o0nO4O1VjVE
      secretKey: HKj8DO5Y5UELPJqNo9GHaWHc0g3g4yyqDH2mutJ6
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  servlet:
    multipart:
      maxFileSize: 100MB # 파일 하나의 최대 크기
      maxRequestSize: 300MB  # 한 번에 최대 업로드 가능 용량
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://changmindb.cr2kywsayi5h.ap-northeast-2.rds.amazonaws.com:3306/carwash?autoReconnect=true
    username: admin
    password: gkfdkqjwl1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 177000

  jpa:
    database: mysql   # 추가 해준 부분
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # 자동으로 테이블을 만들어줌 애플리케이션 실행시에 다 지우고 다시 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true